import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { UserProvider } from "@/Context/UserContext";
import '@fontsource/alegreya'; 
import ClientProviders from "src/proviiders/ClientProviders";
import "flag-icons/css/flag-icons.min.css";
import { Provider } from "react-redux";
import { store } from "@redux/store";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className=""
      >
       {/* <UserProvider>
       <Provider store={store}> */}
         <ClientProviders> 
                    {children} {/* Your main content inside providers */}
                </ClientProviders>
        {/* </Provider>
        </UserProvider> */}
      </body>
    </html>
  );
}
